INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Hakim Ziyech',28,'Attacking Midfielder','Chelsea FC');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Zakaria Aboukhlal',21,'Forward','AZ Alkmaar');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Soufiane Rahimi',25,'Forward','Raja CA');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Youssef El-Arabi',34,'Striker','Olympiacos');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Youssef En-Nesyri',23,'Striker','Sevilla FC');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Ayoub El Kaabi',27,'Striker','Wydad AC');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Munir El Haddadi',25,'Forward','Sevilla FC');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Yahya Jabrane',29,'Midfielder','Wydad AC');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Sofyan Amrabat',24,'Midfielder','ACF Fiorentina');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Aymen Barkok',22,'Midfielder','Eintracht Frankfurt');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Oussama Tannane',27,'Winger','Vitesse Arnhem');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Selim Amallah',24,'Midfielder','Standard Liège');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Adel Taarabt',31,'Attacking Midfielder','SL Benfica');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Achraf Hakimi',22,'Full-back','Inter Milan');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Issam Chebake',31,'Right-back','Yeni Malatyaspor');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Nabil Dirar',35,'Right-back','Club Brugge');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Adam Masina',27,'Left-back','Watford FC');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Sofian Chakla',27,'Centre-back','Getafe CF');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Romain Saïss',31,'Centre-back','Wolverhampton');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Zouhair Feddal',31,'Centre-back','Sporting CP');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Nayef Aguerd',25,'Centre-back','Stade Rennais');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Yassine Bounou',29,'Goalkeeper','Sevilla FC');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Munir Mohamedi',31,'Goalkeeper','Hatayspor');
INSERT INTO Player(id,name,age,position,team) VALUES (nextval('hibernate_sequence'),'Anas Zniti',32,'Goalkeeper','Raja CA');
